// Code generated by protoc-gen-go. DO NOT EDIT.
// source: passengerFeedback.proto

package passengerfeedback

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error int32

const (
	Error_SUCCESS Error = 0
	Error_FAIL    Error = 1
)

var Error_name = map[int32]string{
	0: "SUCCESS",
	1: "FAIL",
}

var Error_value = map[string]int32{
	"SUCCESS": 0,
	"FAIL":    1,
}

func (x Error) String() string {
	return proto.EnumName(Error_name, int32(x))
}

func (Error) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8724f3b5de75954a, []int{0}
}

type PassengerFeedback struct {
	BookingCode          string   `protobuf:"bytes,1,opt,name=bookingCode,proto3" json:"bookingCode,omitempty"`
	PassengerId          int32    `protobuf:"varint,2,opt,name=passengerId,proto3" json:"passengerId,omitempty"`
	Feedback             string   `protobuf:"bytes,3,opt,name=feedback,proto3" json:"feedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PassengerFeedback) Reset()         { *m = PassengerFeedback{} }
func (m *PassengerFeedback) String() string { return proto.CompactTextString(m) }
func (*PassengerFeedback) ProtoMessage()    {}
func (*PassengerFeedback) Descriptor() ([]byte, []int) {
	return fileDescriptor_8724f3b5de75954a, []int{0}
}

func (m *PassengerFeedback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PassengerFeedback.Unmarshal(m, b)
}
func (m *PassengerFeedback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PassengerFeedback.Marshal(b, m, deterministic)
}
func (m *PassengerFeedback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PassengerFeedback.Merge(m, src)
}
func (m *PassengerFeedback) XXX_Size() int {
	return xxx_messageInfo_PassengerFeedback.Size(m)
}
func (m *PassengerFeedback) XXX_DiscardUnknown() {
	xxx_messageInfo_PassengerFeedback.DiscardUnknown(m)
}

var xxx_messageInfo_PassengerFeedback proto.InternalMessageInfo

func (m *PassengerFeedback) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

func (m *PassengerFeedback) GetPassengerId() int32 {
	if m != nil {
		return m.PassengerId
	}
	return 0
}

func (m *PassengerFeedback) GetFeedback() string {
	if m != nil {
		return m.Feedback
	}
	return ""
}

type PassengerFeedbackRequest struct {
	BookingCode          string   `protobuf:"bytes,1,opt,name=bookingCode,proto3" json:"bookingCode,omitempty"`
	PassengerId          int32    `protobuf:"varint,2,opt,name=passengerId,proto3" json:"passengerId,omitempty"`
	Feedback             string   `protobuf:"bytes,3,opt,name=feedback,proto3" json:"feedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PassengerFeedbackRequest) Reset()         { *m = PassengerFeedbackRequest{} }
func (m *PassengerFeedbackRequest) String() string { return proto.CompactTextString(m) }
func (*PassengerFeedbackRequest) ProtoMessage()    {}
func (*PassengerFeedbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8724f3b5de75954a, []int{1}
}

func (m *PassengerFeedbackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PassengerFeedbackRequest.Unmarshal(m, b)
}
func (m *PassengerFeedbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PassengerFeedbackRequest.Marshal(b, m, deterministic)
}
func (m *PassengerFeedbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PassengerFeedbackRequest.Merge(m, src)
}
func (m *PassengerFeedbackRequest) XXX_Size() int {
	return xxx_messageInfo_PassengerFeedbackRequest.Size(m)
}
func (m *PassengerFeedbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PassengerFeedbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PassengerFeedbackRequest proto.InternalMessageInfo

func (m *PassengerFeedbackRequest) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

func (m *PassengerFeedbackRequest) GetPassengerId() int32 {
	if m != nil {
		return m.PassengerId
	}
	return 0
}

func (m *PassengerFeedbackRequest) GetFeedback() string {
	if m != nil {
		return m.Feedback
	}
	return ""
}

type PassengerFeedbackResponse struct {
	Data                 *PassengerFeedback `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ErrorCode            Error              `protobuf:"varint,2,opt,name=errorCode,proto3,enum=passengerfeedback.Error" json:"errorCode,omitempty"`
	Msg                  string             `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PassengerFeedbackResponse) Reset()         { *m = PassengerFeedbackResponse{} }
func (m *PassengerFeedbackResponse) String() string { return proto.CompactTextString(m) }
func (*PassengerFeedbackResponse) ProtoMessage()    {}
func (*PassengerFeedbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8724f3b5de75954a, []int{2}
}

func (m *PassengerFeedbackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PassengerFeedbackResponse.Unmarshal(m, b)
}
func (m *PassengerFeedbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PassengerFeedbackResponse.Marshal(b, m, deterministic)
}
func (m *PassengerFeedbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PassengerFeedbackResponse.Merge(m, src)
}
func (m *PassengerFeedbackResponse) XXX_Size() int {
	return xxx_messageInfo_PassengerFeedbackResponse.Size(m)
}
func (m *PassengerFeedbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PassengerFeedbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PassengerFeedbackResponse proto.InternalMessageInfo

func (m *PassengerFeedbackResponse) GetData() *PassengerFeedback {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *PassengerFeedbackResponse) GetErrorCode() Error {
	if m != nil {
		return m.ErrorCode
	}
	return Error_SUCCESS
}

func (m *PassengerFeedbackResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetPassengerFeedbackByPassengerIdRequest struct {
	PassengerId          int32    `protobuf:"varint,1,opt,name=passengerId,proto3" json:"passengerId,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPassengerFeedbackByPassengerIdRequest) Reset() {
	*m = GetPassengerFeedbackByPassengerIdRequest{}
}
func (m *GetPassengerFeedbackByPassengerIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetPassengerFeedbackByPassengerIdRequest) ProtoMessage()    {}
func (*GetPassengerFeedbackByPassengerIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8724f3b5de75954a, []int{3}
}

func (m *GetPassengerFeedbackByPassengerIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPassengerFeedbackByPassengerIdRequest.Unmarshal(m, b)
}
func (m *GetPassengerFeedbackByPassengerIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPassengerFeedbackByPassengerIdRequest.Marshal(b, m, deterministic)
}
func (m *GetPassengerFeedbackByPassengerIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPassengerFeedbackByPassengerIdRequest.Merge(m, src)
}
func (m *GetPassengerFeedbackByPassengerIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetPassengerFeedbackByPassengerIdRequest.Size(m)
}
func (m *GetPassengerFeedbackByPassengerIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPassengerFeedbackByPassengerIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPassengerFeedbackByPassengerIdRequest proto.InternalMessageInfo

func (m *GetPassengerFeedbackByPassengerIdRequest) GetPassengerId() int32 {
	if m != nil {
		return m.PassengerId
	}
	return 0
}

func (m *GetPassengerFeedbackByPassengerIdRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetPassengerFeedbackByPassengerIdRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type PassengerFeedbackSliceResponse struct {
	Data                 []*PassengerFeedback `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	ErrorCode            Error                `protobuf:"varint,2,opt,name=errorCode,proto3,enum=passengerfeedback.Error" json:"errorCode,omitempty"`
	Msg                  string               `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PassengerFeedbackSliceResponse) Reset()         { *m = PassengerFeedbackSliceResponse{} }
func (m *PassengerFeedbackSliceResponse) String() string { return proto.CompactTextString(m) }
func (*PassengerFeedbackSliceResponse) ProtoMessage()    {}
func (*PassengerFeedbackSliceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8724f3b5de75954a, []int{4}
}

func (m *PassengerFeedbackSliceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PassengerFeedbackSliceResponse.Unmarshal(m, b)
}
func (m *PassengerFeedbackSliceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PassengerFeedbackSliceResponse.Marshal(b, m, deterministic)
}
func (m *PassengerFeedbackSliceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PassengerFeedbackSliceResponse.Merge(m, src)
}
func (m *PassengerFeedbackSliceResponse) XXX_Size() int {
	return xxx_messageInfo_PassengerFeedbackSliceResponse.Size(m)
}
func (m *PassengerFeedbackSliceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PassengerFeedbackSliceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PassengerFeedbackSliceResponse proto.InternalMessageInfo

func (m *PassengerFeedbackSliceResponse) GetData() []*PassengerFeedback {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *PassengerFeedbackSliceResponse) GetErrorCode() Error {
	if m != nil {
		return m.ErrorCode
	}
	return Error_SUCCESS
}

func (m *PassengerFeedbackSliceResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type PassengerFeedbackByBookingCodeRequest struct {
	BookingCode          string   `protobuf:"bytes,1,opt,name=bookingCode,proto3" json:"bookingCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PassengerFeedbackByBookingCodeRequest) Reset()         { *m = PassengerFeedbackByBookingCodeRequest{} }
func (m *PassengerFeedbackByBookingCodeRequest) String() string { return proto.CompactTextString(m) }
func (*PassengerFeedbackByBookingCodeRequest) ProtoMessage()    {}
func (*PassengerFeedbackByBookingCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8724f3b5de75954a, []int{5}
}

func (m *PassengerFeedbackByBookingCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PassengerFeedbackByBookingCodeRequest.Unmarshal(m, b)
}
func (m *PassengerFeedbackByBookingCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PassengerFeedbackByBookingCodeRequest.Marshal(b, m, deterministic)
}
func (m *PassengerFeedbackByBookingCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PassengerFeedbackByBookingCodeRequest.Merge(m, src)
}
func (m *PassengerFeedbackByBookingCodeRequest) XXX_Size() int {
	return xxx_messageInfo_PassengerFeedbackByBookingCodeRequest.Size(m)
}
func (m *PassengerFeedbackByBookingCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PassengerFeedbackByBookingCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PassengerFeedbackByBookingCodeRequest proto.InternalMessageInfo

func (m *PassengerFeedbackByBookingCodeRequest) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

type DeletePassengerFeedbackByPassengerIdRequest struct {
	PassengerId          int32    `protobuf:"varint,1,opt,name=passengerId,proto3" json:"passengerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePassengerFeedbackByPassengerIdRequest) Reset() {
	*m = DeletePassengerFeedbackByPassengerIdRequest{}
}
func (m *DeletePassengerFeedbackByPassengerIdRequest) String() string {
	return proto.CompactTextString(m)
}
func (*DeletePassengerFeedbackByPassengerIdRequest) ProtoMessage() {}
func (*DeletePassengerFeedbackByPassengerIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8724f3b5de75954a, []int{6}
}

func (m *DeletePassengerFeedbackByPassengerIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePassengerFeedbackByPassengerIdRequest.Unmarshal(m, b)
}
func (m *DeletePassengerFeedbackByPassengerIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePassengerFeedbackByPassengerIdRequest.Marshal(b, m, deterministic)
}
func (m *DeletePassengerFeedbackByPassengerIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePassengerFeedbackByPassengerIdRequest.Merge(m, src)
}
func (m *DeletePassengerFeedbackByPassengerIdRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePassengerFeedbackByPassengerIdRequest.Size(m)
}
func (m *DeletePassengerFeedbackByPassengerIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePassengerFeedbackByPassengerIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePassengerFeedbackByPassengerIdRequest proto.InternalMessageInfo

func (m *DeletePassengerFeedbackByPassengerIdRequest) GetPassengerId() int32 {
	if m != nil {
		return m.PassengerId
	}
	return 0
}

type ErrorCodeAndMessageResponse struct {
	ErrorCode            Error    `protobuf:"varint,1,opt,name=errorCode,proto3,enum=passengerfeedback.Error" json:"errorCode,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorCodeAndMessageResponse) Reset()         { *m = ErrorCodeAndMessageResponse{} }
func (m *ErrorCodeAndMessageResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorCodeAndMessageResponse) ProtoMessage()    {}
func (*ErrorCodeAndMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8724f3b5de75954a, []int{7}
}

func (m *ErrorCodeAndMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorCodeAndMessageResponse.Unmarshal(m, b)
}
func (m *ErrorCodeAndMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorCodeAndMessageResponse.Marshal(b, m, deterministic)
}
func (m *ErrorCodeAndMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorCodeAndMessageResponse.Merge(m, src)
}
func (m *ErrorCodeAndMessageResponse) XXX_Size() int {
	return xxx_messageInfo_ErrorCodeAndMessageResponse.Size(m)
}
func (m *ErrorCodeAndMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorCodeAndMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorCodeAndMessageResponse proto.InternalMessageInfo

func (m *ErrorCodeAndMessageResponse) GetErrorCode() Error {
	if m != nil {
		return m.ErrorCode
	}
	return Error_SUCCESS
}

func (m *ErrorCodeAndMessageResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterEnum("passengerfeedback.Error", Error_name, Error_value)
	proto.RegisterType((*PassengerFeedback)(nil), "passengerfeedback.PassengerFeedback")
	proto.RegisterType((*PassengerFeedbackRequest)(nil), "passengerfeedback.PassengerFeedbackRequest")
	proto.RegisterType((*PassengerFeedbackResponse)(nil), "passengerfeedback.PassengerFeedbackResponse")
	proto.RegisterType((*GetPassengerFeedbackByPassengerIdRequest)(nil), "passengerfeedback.GetPassengerFeedbackByPassengerIdRequest")
	proto.RegisterType((*PassengerFeedbackSliceResponse)(nil), "passengerfeedback.PassengerFeedbackSliceResponse")
	proto.RegisterType((*PassengerFeedbackByBookingCodeRequest)(nil), "passengerfeedback.PassengerFeedbackByBookingCodeRequest")
	proto.RegisterType((*DeletePassengerFeedbackByPassengerIdRequest)(nil), "passengerfeedback.DeletePassengerFeedbackByPassengerIdRequest")
	proto.RegisterType((*ErrorCodeAndMessageResponse)(nil), "passengerfeedback.ErrorCodeAndMessageResponse")
}

func init() { proto.RegisterFile("passengerFeedback.proto", fileDescriptor_8724f3b5de75954a) }

var fileDescriptor_8724f3b5de75954a = []byte{
	// 450 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x95, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0x86, 0x33, 0xdb, 0x66, 0xed, 0x9e, 0x82, 0x74, 0x87, 0x45, 0x63, 0x16, 0x96, 0x32, 0x28,
	0x14, 0x57, 0x02, 0x56, 0x90, 0x05, 0x41, 0xd8, 0xad, 0x5d, 0x29, 0x28, 0x2e, 0x09, 0x3e, 0x40,
	0xba, 0x73, 0x1a, 0xc2, 0xb6, 0x99, 0x9a, 0x19, 0x2f, 0xec, 0xb5, 0x97, 0x82, 0x8f, 0xe0, 0x8d,
	0xe0, 0x6b, 0x4a, 0xa6, 0x69, 0x92, 0x36, 0x23, 0xa4, 0xa0, 0x78, 0xd7, 0x99, 0x39, 0x73, 0xfe,
	0xff, 0x7c, 0xfd, 0x87, 0xc0, 0xc3, 0x65, 0x28, 0x25, 0x26, 0x11, 0xa6, 0xd7, 0x88, 0x7c, 0x1a,
	0xde, 0xde, 0x79, 0xcb, 0x54, 0x28, 0x41, 0x8f, 0x8b, 0x83, 0x59, 0x7e, 0xc0, 0x24, 0x1c, 0xdf,
	0xec, 0x56, 0xd3, 0x3e, 0x74, 0xa7, 0x42, 0xdc, 0xc5, 0x49, 0x34, 0x12, 0x1c, 0x1d, 0xd2, 0x27,
	0x83, 0x23, 0xbf, 0xba, 0x95, 0x55, 0x14, 0xbd, 0x26, 0xdc, 0x39, 0xe8, 0x93, 0x81, 0xed, 0x57,
	0xb7, 0xa8, 0x0b, 0x9d, 0x8d, 0x88, 0xd3, 0xd2, 0x0d, 0x8a, 0x35, 0x5b, 0x81, 0x53, 0x13, 0xf5,
	0xf1, 0xd3, 0x67, 0x94, 0xea, 0x9f, 0x6b, 0xff, 0x20, 0xf0, 0xc8, 0x20, 0x2e, 0x97, 0x22, 0x91,
	0x48, 0x2f, 0xa0, 0xcd, 0x43, 0x15, 0x6a, 0xd9, 0xee, 0xf0, 0xb1, 0x57, 0x03, 0xe6, 0xd5, 0xef,
	0xea, 0x1b, 0xf4, 0x25, 0x1c, 0x61, 0x9a, 0x8a, 0x54, 0xbb, 0xce, 0x3c, 0xdd, 0x1f, 0x3a, 0x86,
	0xeb, 0xe3, 0xac, 0xc6, 0x2f, 0x4b, 0x69, 0x0f, 0x5a, 0x0b, 0x19, 0xe5, 0x36, 0xb3, 0x9f, 0x6c,
	0x05, 0x83, 0xb7, 0xa8, 0x6a, 0x3a, 0x57, 0x5f, 0x6e, 0xca, 0x11, 0x2b, 0xb4, 0xaa, 0x2c, 0x48,
	0x9d, 0xc5, 0x03, 0x38, 0x14, 0xb3, 0x99, 0x44, 0x95, 0x83, 0xca, 0x57, 0xf4, 0x04, 0xec, 0x79,
	0xbc, 0x88, 0x95, 0x56, 0xb6, 0xfd, 0xf5, 0x82, 0xfd, 0x24, 0x70, 0x56, 0x53, 0x0e, 0xe6, 0xf1,
	0x2d, 0x1a, 0x10, 0xb5, 0xfe, 0x1b, 0xa2, 0x09, 0x3c, 0x31, 0xf0, 0xb9, 0x2a, 0x43, 0xd2, 0x38,
	0x4d, 0xec, 0x03, 0x9c, 0xbf, 0xc1, 0x39, 0x2a, 0xfc, 0x4b, 0xc0, 0x59, 0x04, 0xa7, 0xe3, 0x8d,
	0xf5, 0xcb, 0x84, 0xbf, 0x47, 0x29, 0xc3, 0xa8, 0xc4, 0xb7, 0x05, 0x81, 0xec, 0x0d, 0xe1, 0xa0,
	0x80, 0xf0, 0xf4, 0x0c, 0x6c, 0x5d, 0x45, 0xbb, 0x70, 0x2f, 0xf8, 0x38, 0x1a, 0x8d, 0x83, 0xa0,
	0x67, 0xd1, 0x0e, 0xb4, 0xaf, 0x2f, 0x27, 0xef, 0x7a, 0x64, 0xf8, 0xab, 0x0d, 0x9d, 0xe2, 0x49,
	0x4b, 0x38, 0x09, 0x39, 0xaf, 0x3f, 0xf5, 0xf3, 0x46, 0xff, 0xdf, 0x7a, 0x78, 0xf7, 0x59, 0xb3,
	0xe2, 0xf5, 0xa4, 0xcc, 0xa2, 0xdf, 0x08, 0x38, 0x11, 0x2a, 0x23, 0x50, 0xfa, 0xca, 0xd0, 0xac,
	0x69, 0xee, 0xdd, 0xe7, 0x4d, 0x9c, 0x6c, 0xe5, 0x96, 0x59, 0xf4, 0xeb, 0xae, 0x9d, 0x4a, 0x60,
	0xe8, 0x45, 0x93, 0x8e, 0xa6, 0x8c, 0xed, 0x4d, 0xe5, 0x3b, 0x81, 0x53, 0xae, 0x23, 0x67, 0x06,
	0xf3, 0xda, 0xd0, 0x6f, 0x8f, 0x88, 0xba, 0xde, 0x9f, 0xe2, 0x64, 0x4e, 0x24, 0xb3, 0xa6, 0x87,
	0xfa, 0xf3, 0xf0, 0xe2, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xec, 0x20, 0xb7, 0x4d, 0x39, 0x06,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FeedbackClient is the client API for Feedback service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FeedbackClient interface {
	AddPassengerFeedback(ctx context.Context, in *PassengerFeedbackRequest, opts ...grpc.CallOption) (*PassengerFeedbackResponse, error)
	GetFeedbackByPassengerId(ctx context.Context, in *GetPassengerFeedbackByPassengerIdRequest, opts ...grpc.CallOption) (*PassengerFeedbackSliceResponse, error)
	GetFeedbackByBookingCode(ctx context.Context, in *PassengerFeedbackByBookingCodeRequest, opts ...grpc.CallOption) (*PassengerFeedbackResponse, error)
	DeleteFeedbackByPassengerId(ctx context.Context, in *DeletePassengerFeedbackByPassengerIdRequest, opts ...grpc.CallOption) (*ErrorCodeAndMessageResponse, error)
}

type feedbackClient struct {
	cc *grpc.ClientConn
}

func NewFeedbackClient(cc *grpc.ClientConn) FeedbackClient {
	return &feedbackClient{cc}
}

func (c *feedbackClient) AddPassengerFeedback(ctx context.Context, in *PassengerFeedbackRequest, opts ...grpc.CallOption) (*PassengerFeedbackResponse, error) {
	out := new(PassengerFeedbackResponse)
	err := c.cc.Invoke(ctx, "/passengerfeedback.Feedback/addPassengerFeedback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedbackClient) GetFeedbackByPassengerId(ctx context.Context, in *GetPassengerFeedbackByPassengerIdRequest, opts ...grpc.CallOption) (*PassengerFeedbackSliceResponse, error) {
	out := new(PassengerFeedbackSliceResponse)
	err := c.cc.Invoke(ctx, "/passengerfeedback.Feedback/getFeedbackByPassengerId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedbackClient) GetFeedbackByBookingCode(ctx context.Context, in *PassengerFeedbackByBookingCodeRequest, opts ...grpc.CallOption) (*PassengerFeedbackResponse, error) {
	out := new(PassengerFeedbackResponse)
	err := c.cc.Invoke(ctx, "/passengerfeedback.Feedback/getFeedbackByBookingCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedbackClient) DeleteFeedbackByPassengerId(ctx context.Context, in *DeletePassengerFeedbackByPassengerIdRequest, opts ...grpc.CallOption) (*ErrorCodeAndMessageResponse, error) {
	out := new(ErrorCodeAndMessageResponse)
	err := c.cc.Invoke(ctx, "/passengerfeedback.Feedback/deleteFeedbackByPassengerId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeedbackServer is the server API for Feedback service.
type FeedbackServer interface {
	AddPassengerFeedback(context.Context, *PassengerFeedbackRequest) (*PassengerFeedbackResponse, error)
	GetFeedbackByPassengerId(context.Context, *GetPassengerFeedbackByPassengerIdRequest) (*PassengerFeedbackSliceResponse, error)
	GetFeedbackByBookingCode(context.Context, *PassengerFeedbackByBookingCodeRequest) (*PassengerFeedbackResponse, error)
	DeleteFeedbackByPassengerId(context.Context, *DeletePassengerFeedbackByPassengerIdRequest) (*ErrorCodeAndMessageResponse, error)
}

// UnimplementedFeedbackServer can be embedded to have forward compatible implementations.
type UnimplementedFeedbackServer struct {
}

func (*UnimplementedFeedbackServer) AddPassengerFeedback(ctx context.Context, req *PassengerFeedbackRequest) (*PassengerFeedbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPassengerFeedback not implemented")
}
func (*UnimplementedFeedbackServer) GetFeedbackByPassengerId(ctx context.Context, req *GetPassengerFeedbackByPassengerIdRequest) (*PassengerFeedbackSliceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeedbackByPassengerId not implemented")
}
func (*UnimplementedFeedbackServer) GetFeedbackByBookingCode(ctx context.Context, req *PassengerFeedbackByBookingCodeRequest) (*PassengerFeedbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeedbackByBookingCode not implemented")
}
func (*UnimplementedFeedbackServer) DeleteFeedbackByPassengerId(ctx context.Context, req *DeletePassengerFeedbackByPassengerIdRequest) (*ErrorCodeAndMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFeedbackByPassengerId not implemented")
}

func RegisterFeedbackServer(s *grpc.Server, srv FeedbackServer) {
	s.RegisterService(&_Feedback_serviceDesc, srv)
}

func _Feedback_AddPassengerFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PassengerFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServer).AddPassengerFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/passengerfeedback.Feedback/AddPassengerFeedback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServer).AddPassengerFeedback(ctx, req.(*PassengerFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feedback_GetFeedbackByPassengerId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPassengerFeedbackByPassengerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServer).GetFeedbackByPassengerId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/passengerfeedback.Feedback/GetFeedbackByPassengerId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServer).GetFeedbackByPassengerId(ctx, req.(*GetPassengerFeedbackByPassengerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feedback_GetFeedbackByBookingCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PassengerFeedbackByBookingCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServer).GetFeedbackByBookingCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/passengerfeedback.Feedback/GetFeedbackByBookingCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServer).GetFeedbackByBookingCode(ctx, req.(*PassengerFeedbackByBookingCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feedback_DeleteFeedbackByPassengerId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePassengerFeedbackByPassengerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServer).DeleteFeedbackByPassengerId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/passengerfeedback.Feedback/DeleteFeedbackByPassengerId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServer).DeleteFeedbackByPassengerId(ctx, req.(*DeletePassengerFeedbackByPassengerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Feedback_serviceDesc = grpc.ServiceDesc{
	ServiceName: "passengerfeedback.Feedback",
	HandlerType: (*FeedbackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addPassengerFeedback",
			Handler:    _Feedback_AddPassengerFeedback_Handler,
		},
		{
			MethodName: "getFeedbackByPassengerId",
			Handler:    _Feedback_GetFeedbackByPassengerId_Handler,
		},
		{
			MethodName: "getFeedbackByBookingCode",
			Handler:    _Feedback_GetFeedbackByBookingCode_Handler,
		},
		{
			MethodName: "deleteFeedbackByPassengerId",
			Handler:    _Feedback_DeleteFeedbackByPassengerId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "passengerFeedback.proto",
}
